OMP_DIRS  := backprop bfs cfd heartwall hotspot kmeans lavaMD leukocyte lud nn nw srad streamcluster particlefilter pathfinder mummergpu

all:
	$(MAKE) backprop install
	$(MAKE) bfs install
	$(MAKE) cfd install
	$(MAKE) heartwall install
	$(MAKE) hotspot install
	$(MAKE) kmeans/kmeans_openmp install
	$(MAKE) lavaMD install
	$(MAKE) leukocyte install
	$(MAKE) lud install
	$(MAKE) nn install
	$(MAKE) nw install
	$(MAKE) srad/srad_v1 install
	$(MAKE) srad/srad_v2 install
	$(MAKE) streamcluster install
	$(MAKE) particlefilter install
	$(MAKE) pathfinder install
	$(MAKE) mummergpu install

clean:
	$(MAKE) backprop clean
	$(MAKE) bfs clean
	$(MAKE) cfd clean
	$(MAKE) heartwall clean
	$(MAKE) hotspot clean
	$(MAKE) kmeans/kmeans_openmp clean
	$(MAKE) lavaMD clean
	$(MAKE) leukocyte clean
	$(MAKE) lud clean
	$(MAKE) nn clean
	$(MAKE) nw clean
	$(MAKE) srad/srad_v1 clean
	$(MAKE) srad/srad_v2 clean
	$(MAKE) streamcluster clean
	$(MAKE) particlefilter clean
	$(MAKE) pathfinder clean
	$(MAKE) mummergpu clean
